[project]
name = "lol-ml"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi==0.135.1",
    "joblib==1.5.3",
    "numpy==2.4.3",
    "pandas==3.0.1",
    "pydantic==2.12.5",
    "python-dotenv==1.2.2",
    "scikit-learn==1.8.0",
    "supabase==2.28.3",
    "torch>=2.14.0",
    "uvicorn==0.41.0",
]

[dependency-groups]
dev = [
    "jupyter==1.1.1",
    "matplotlib==3.10.8",
]
